---
# tasks file for ansible-ntp
- name: install ntp
  apt:
    name: ntp
    state: present
    update_cache: true

- name: generate_config
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    mode: 0644
    owner: root
    group: root

- name: start ntp service
  service:
    name: ntp
    state: started

    




